//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_ex
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявка
    {
        

        public int id_заявки { get; set; }
        public string Описание_заявки { get; set; }
        public System.DateTime Дата_открытия { get; set; }
        public int id_оборудования { get; set; }
        public int id_неисправности { get; set; }
        public int id_клиента { get; set; }
        public Nullable<int> id_исполнителя { get; set; }
        public Nullable<int> id_статуса { get; set; }
        public Nullable<decimal> Итоговая_стоимость { get; set; }
        public Nullable<System.DateTime> Дата_закрытия { get; set; }
        public Nullable<int> Приоритет { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual Неисправность Неисправность { get; set; }
        public virtual Оборудование Оборудование { get; set; }
        public virtual Приоритет Приоритет1 { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
        public virtual Статус Статус { get; set; }
        public Заявка(string desc, DateTime dateTime, int eqtype, int deftype, int clientid, object p1, object p2, object p3, object p4, object p5)
        {
            this.Описание_заявки = desc;
            this.Дата_открытия = dateTime;
            this.id_оборудования = eqtype;
            this.id_неисправности = deftype;
            this.id_клиента = clientid;
            this.id_исполнителя = (int?)p1;
            this.id_статуса = (int?)p2;
            this.Итоговая_стоимость = (decimal?)p3;
            this.Дата_закрытия = (DateTime?)p4;
            this.Приоритет = (int?)p5;
        }
        public Заявка()
        {

        }
    }
}
