//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_ex
{
    using System;
    using System.Collections.Generic;
    
    public partial class Запчасть
    {
        public int id_запчасти { get; set; }
        public string Наименование { get; set; }
        public int id_оборудования { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public string Наличие { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Оборудование Оборудование { get; set; }
    }
}
